CREATE TABLE 'PERSON'(
	'PERSON_ID' int NOT NULL AUTO_INCREMENT,
	'PERSON_FIRSTNAME' varchar(45) DEFAULT NULL,
	'PERSON_LASTNAME' varchar(45) DEFAULT NULL,
	'PERSON_GENDER' varchar(45) DEFAULT NULL,
	'PERSON_AGE' int DEFAULT NULL,
	PRIMARY KEY('PERSON_ID')
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;